#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>

class View;

namespace Ui {
    class MainWindow;
}

class DataBinding;

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    void dataBind();
    QList<DataBinding*> m_bindings;

    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;
};

#endif // MAINWINDOW_H
